name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download UPX
        run: Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-win64.zip" -OutFile "upx.zip"
      - name: Extract UPX
        run: Expand-Archive -Path "upx.zip" -DestinationPath "../upx"
      - name: Build with cargo
        run: cargo build --release --verbose
      - name: Compress with UPX
        run: ..\upx\upx-4.2.4-win64\upx.exe --best --all-methods --all-filters --force -o MewAuto.exe target/release/MewAuto.exe
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MewAuto
          path: MewAuto.exe
